import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

async function seed() {
  console.log("Seeding database...");

  // Clear existing data
  await db.activityAlert.deleteMany();
  await db.restaurantAlert.deleteMany();
  await db.reservation.deleteMany();
  await db.userProfile.deleteMany();
  await db.restaurant.deleteMany();

  const restaurants = [
    {
      name: "Frantzén",
      address: "Klara Norra Kyrkogata 26, 111 22 Stockholm",
      cuisine: "New Nordic",
      neighborhood: "City",
      rating: 4.9,
      reviewCount: 1243,
      priceLevel: 4,
      image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
      description: "Three Michelin-starred restaurant offering a unique multi-sensory dining experience. Chef Björn Frantzén combines Nordic traditions with Asian influences in an intimate setting spread across three floors.",
      tags: JSON.stringify(["Fine Dining", "Michelin Star", "Tasting Menu"]),
      timesBookedOnReslot: 87,
      seatType: "Inomhus",
      instagram: "@restaurantfrantzen",
      website: "https://frantzen.com",
      vibeTags: JSON.stringify(["Intimate", "Elegant", "World-class"]),
      goodForTags: JSON.stringify(["Special Occasions", "Date Night", "Business Dinner"]),
      foodTags: JSON.stringify(["Nordic", "Japanese", "Tasting Menu", "Seasonal"]),
      latitude: 59.3345,
      longitude: 18.0632,
      isExclusive: true,
      city: "Stockholm",
    },
    {
      name: "Babette",
      address: "Roslagsgatan 6, 113 55 Stockholm",
      cuisine: "French-Nordic",
      neighborhood: "Östermalm",
      rating: 4.7,
      reviewCount: 856,
      priceLevel: 3,
      image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop",
      description: "A beloved neighborhood bistro blending French technique with Nordic ingredients. Known for its warm atmosphere, natural wines, and seasonal menus that celebrate local produce.",
      tags: JSON.stringify(["Bistro", "Natural Wine", "Seasonal"]),
      timesBookedOnReslot: 62,
      seatType: "Båda",
      instagram: "@babettestockholm",
      website: "https://babette.se",
      vibeTags: JSON.stringify(["Cozy", "Relaxed", "Charming"]),
      goodForTags: JSON.stringify(["Date Night", "Friends Dinner", "Casual Evening"]),
      foodTags: JSON.stringify(["French", "Nordic", "Bistro", "Natural Wine"]),
      latitude: 59.3462,
      longitude: 18.0615,
      isExclusive: false,
      city: "Stockholm",
    },
    {
      name: "Punk Royale",
      address: "Folkungagatan 128, 116 30 Stockholm",
      cuisine: "Avant-garde",
      neighborhood: "Södermalm",
      rating: 4.6,
      reviewCount: 734,
      priceLevel: 4,
      image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
      description: "Stockholm's most provocative dining experience. Punk Royale breaks every rule of fine dining with theatrical presentations, unexpected flavor combinations, and a rock'n'roll atmosphere.",
      tags: JSON.stringify(["Avant-garde", "Theatrical", "Experience Dining"]),
      timesBookedOnReslot: 54,
      seatType: "Inomhus",
      instagram: "@punkroyale",
      website: "https://punkroyale.se",
      vibeTags: JSON.stringify(["Wild", "Theatrical", "Unforgettable"]),
      goodForTags: JSON.stringify(["Special Occasions", "Group Dinner", "Birthday"]),
      foodTags: JSON.stringify(["Avant-garde", "Creative", "Tasting Menu"]),
      latitude: 59.3153,
      longitude: 18.0874,
      isExclusive: true,
      city: "Stockholm",
    },
    {
      name: "Ekstedt",
      address: "Humlegårdsgatan 17, 114 46 Stockholm",
      cuisine: "Fire-cooked Nordic",
      neighborhood: "Östermalm",
      rating: 4.8,
      reviewCount: 1087,
      priceLevel: 4,
      image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800",
      description: "Michelin-starred restaurant where all cooking is done over open fire, wood oven, and smoke. Chef Niklas Ekstedt brings ancient Scandinavian cooking techniques to modern fine dining.",
      tags: JSON.stringify(["Michelin Star", "Open Fire", "Nordic"]),
      timesBookedOnReslot: 73,
      seatType: "Inomhus",
      instagram: "@ekstedtrestaurant",
      website: "https://ekstedt.nu",
      vibeTags: JSON.stringify(["Rustic Elegant", "Warm", "Authentic"]),
      goodForTags: JSON.stringify(["Date Night", "Special Occasions", "Food Enthusiasts"]),
      foodTags: JSON.stringify(["Nordic", "Fire-cooked", "Seasonal", "Smoke"]),
      latitude: 59.3400,
      longitude: 18.0750,
      isExclusive: false,
      city: "Stockholm",
    },
    {
      name: "Oaxen Krog",
      address: "Beckholmsvägen 26, 115 21 Stockholm",
      cuisine: "Modern Swedish",
      neighborhood: "City",
      rating: 4.8,
      reviewCount: 968,
      priceLevel: 4,
      image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800",
      description: "Two Michelin-starred waterfront restaurant on Djurgården. Chef Magnus Ek creates extraordinary dishes from foraged ingredients and the finest Swedish produce in a stunning maritime setting.",
      tags: JSON.stringify(["Michelin Star", "Waterfront", "Foraging"]),
      timesBookedOnReslot: 65,
      seatType: "Båda",
      instagram: "@oaxen",
      website: "https://oaxen.com",
      vibeTags: JSON.stringify(["Serene", "Waterfront", "Refined"]),
      goodForTags: JSON.stringify(["Special Occasions", "Anniversary", "Business Dinner"]),
      foodTags: JSON.stringify(["Modern Swedish", "Foraged", "Tasting Menu", "Seafood"]),
      latitude: 59.3240,
      longitude: 18.1120,
      isExclusive: false,
      city: "Stockholm",
    },
    {
      name: "Gastrologik",
      address: "Artillerigatan 14, 114 51 Stockholm",
      cuisine: "Seasonal Tasting",
      neighborhood: "Östermalm",
      rating: 4.7,
      reviewCount: 812,
      priceLevel: 4,
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
      description: "A no-menu restaurant where every dish is created from the day's best ingredients. Chefs Anton Bjuhr and Jacob Holmström craft surprise tasting menus that celebrate Swedish terroir.",
      tags: JSON.stringify(["No Menu", "Tasting Menu", "Seasonal"]),
      timesBookedOnReslot: 48,
      seatType: "Inomhus",
      instagram: "@gastrologik",
      website: "https://gastrologik.se",
      vibeTags: JSON.stringify(["Minimalist", "Sophisticated", "Surprising"]),
      goodForTags: JSON.stringify(["Date Night", "Food Enthusiasts", "Special Occasions"]),
      foodTags: JSON.stringify(["Seasonal", "Swedish", "Tasting Menu", "Surprise"]),
      latitude: 59.3380,
      longitude: 18.0800,
      isExclusive: true,
      city: "Stockholm",
    },
    {
      name: "Taverna Brillo",
      address: "Sturegatan 6, 114 35 Stockholm",
      cuisine: "Italian-Nordic",
      neighborhood: "Östermalm",
      rating: 4.4,
      reviewCount: 1456,
      priceLevel: 2,
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
      description: "A vibrant all-day restaurant and bar in the heart of Stureplan. Serving Italian-inspired dishes with Nordic touches, fresh pasta, wood-fired pizzas, and creative cocktails in a buzzing atmosphere.",
      tags: JSON.stringify(["Italian", "Cocktails", "All-day"]),
      timesBookedOnReslot: 112,
      seatType: "Båda",
      instagram: "@tavernabrillo",
      website: "https://tavernabrillo.se",
      vibeTags: JSON.stringify(["Buzzing", "Social", "Trendy"]),
      goodForTags: JSON.stringify(["After Work", "Friends Dinner", "Casual Date"]),
      foodTags: JSON.stringify(["Italian", "Pasta", "Pizza", "Cocktails"]),
      latitude: 59.3380,
      longitude: 18.0730,
      isExclusive: false,
      city: "Stockholm",
    },
    {
      name: "Sushi Sho",
      address: "Upplandsgatan 45, 113 28 Stockholm",
      cuisine: "Omakase",
      neighborhood: "Vasastan",
      rating: 4.9,
      reviewCount: 687,
      priceLevel: 4,
      image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800",
      description: "Stockholm's premier omakase experience. Master sushi chef Carl Ishizaki serves an intimate 20-course omakase using the finest fish flown in from Tokyo's Tsukiji market, paired with rare sake.",
      tags: JSON.stringify(["Omakase", "Sushi", "Intimate"]),
      timesBookedOnReslot: 93,
      seatType: "Inomhus",
      instagram: "@sushisho",
      website: "https://sushisho.se",
      vibeTags: JSON.stringify(["Intimate", "Zen", "Authentic"]),
      goodForTags: JSON.stringify(["Date Night", "Special Occasions", "Sushi Lovers"]),
      foodTags: JSON.stringify(["Japanese", "Omakase", "Sushi", "Sake"]),
      latitude: 59.3440,
      longitude: 18.0530,
      isExclusive: true,
      city: "Stockholm",
    },
    // Göteborg
    {
      name: "Bhoga",
      address: "Norra Hamngatan 10, 411 14 Göteborg",
      cuisine: "New Nordic",
      neighborhood: "Centrum",
      rating: 4.8,
      reviewCount: 743,
      priceLevel: 4,
      image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
      description: "Michelin-starred restaurant in Göteborg's historic center. Chef Gustav Knutsson creates innovative Nordic cuisine with foraged ingredients and hyper-local produce.",
      tags: JSON.stringify(["Michelin Star", "Nordic", "Tasting Menu"]),
      timesBookedOnReslot: 41,
      seatType: "Inomhus",
      instagram: "@bhoga_gbg",
      website: "https://bhoga.se",
      vibeTags: JSON.stringify(["Elegant", "Intimate", "Refined"]),
      goodForTags: JSON.stringify(["Date Night", "Special Occasions", "Food Lovers"]),
      foodTags: JSON.stringify(["Nordic", "Seasonal", "Tasting Menu"]),
      latitude: 57.7089,
      longitude: 11.9746,
      isExclusive: true,
      city: "Göteborg",
    },
    {
      name: "Koka",
      address: "Viktoriagatan 12, 411 25 Göteborg",
      cuisine: "Modern Swedish",
      neighborhood: "Vasastan",
      rating: 4.6,
      reviewCount: 612,
      priceLevel: 3,
      image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
      description: "A Göteborg institution celebrating local ingredients and seasonal cooking. Relaxed atmosphere with ambitious cooking.",
      tags: JSON.stringify(["Seasonal", "Local", "Bistro"]),
      timesBookedOnReslot: 38,
      seatType: "Båda",
      instagram: "@koka_gbg",
      website: "https://koka.se",
      vibeTags: JSON.stringify(["Cozy", "Relaxed", "Neighborhood"]),
      goodForTags: JSON.stringify(["Friends Dinner", "Date Night", "Casual"]),
      foodTags: JSON.stringify(["Swedish", "Seasonal", "Local"]),
      latitude: 57.6992,
      longitude: 11.9637,
      isExclusive: false,
      city: "Göteborg",
    },
    {
      name: "Upper House Dining",
      address: "Mässans gata 24, 412 51 Göteborg",
      cuisine: "New Nordic",
      neighborhood: "Centrum",
      rating: 4.7,
      reviewCount: 523,
      priceLevel: 4,
      image: "https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=800",
      description: "Exclusive fine dining at the top of Gothia Towers with panoramic views over Göteborg. Chef crafts refined New Nordic tasting menus with world-class ingredients.",
      tags: JSON.stringify(["Fine Dining", "Views", "Tasting Menu"]),
      timesBookedOnReslot: 34,
      seatType: "Inomhus",
      instagram: "@upperhouse_gbg",
      website: "https://upperhouse.se",
      vibeTags: JSON.stringify(["Elegant", "Panoramic", "Exclusive"]),
      goodForTags: JSON.stringify(["Special Occasions", "Business Dinner", "Anniversary"]),
      foodTags: JSON.stringify(["Nordic", "Tasting Menu", "Seasonal"]),
      latitude: 57.6969,
      longitude: 11.9904,
      isExclusive: true,
      city: "Göteborg",
    },
    {
      name: "SK Mat & Människor",
      address: "Johannebergsgatan 24, 412 55 Göteborg",
      cuisine: "Swedish Seasonal",
      neighborhood: "Haga",
      rating: 4.5,
      reviewCount: 834,
      priceLevel: 3,
      image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800",
      description: "A neighborhood bistro in Haga serving honest Swedish seasonal cooking. Warm atmosphere with a focus on local ingredients and community spirit.",
      tags: JSON.stringify(["Seasonal", "Bistro", "Local"]),
      timesBookedOnReslot: 27,
      seatType: "Båda",
      instagram: "@skmat_gbg",
      website: "https://skmat.se",
      vibeTags: JSON.stringify(["Cozy", "Neighborhood", "Warm"]),
      goodForTags: JSON.stringify(["Friends Dinner", "Casual Date", "Weeknight"]),
      foodTags: JSON.stringify(["Swedish", "Seasonal", "Bistro"]),
      latitude: 57.6935,
      longitude: 11.9590,
      isExclusive: false,
      city: "Göteborg",
    },
    {
      name: "Thörnströms Kök",
      address: "Teknologgatan 3, 411 32 Göteborg",
      cuisine: "French-Nordic",
      neighborhood: "Vasastan",
      rating: 4.6,
      reviewCount: 712,
      priceLevel: 3,
      image: "https://images.unsplash.com/photo-1515669097368-22e68427d265?w=800",
      description: "A Göteborg classic blending French technique with Nordic soul. Intimate dining room with impeccable service and a celebrated wine list.",
      tags: JSON.stringify(["French", "Nordic", "Wine"]),
      timesBookedOnReslot: 32,
      seatType: "Inomhus",
      instagram: "@thornstromskok",
      website: "https://thornstromskok.se",
      vibeTags: JSON.stringify(["Classic", "Intimate", "Refined"]),
      goodForTags: JSON.stringify(["Date Night", "Anniversary", "Business Dinner"]),
      foodTags: JSON.stringify(["French", "Nordic", "Wine Pairing"]),
      latitude: 57.6988,
      longitude: 11.9700,
      isExclusive: false,
      city: "Göteborg",
    },
    {
      name: "Sjömagasinet",
      address: "Klippans Kulturreservat, 414 51 Göteborg",
      cuisine: "Seafood",
      neighborhood: "Majorna",
      rating: 4.7,
      reviewCount: 645,
      priceLevel: 4,
      image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
      description: "Iconic waterfront seafood restaurant in a historic warehouse. Fresh catches from the West Coast prepared with Nordic finesse in a stunning harbor setting.",
      tags: JSON.stringify(["Seafood", "Waterfront", "Fine Dining"]),
      timesBookedOnReslot: 38,
      seatType: "Båda",
      instagram: "@sjomagasinet_gbg",
      website: "https://sjomagasinet.se",
      vibeTags: JSON.stringify(["Waterfront", "Classic", "Elegant"]),
      goodForTags: JSON.stringify(["Special Occasions", "Business Dinner", "Seafood Lovers"]),
      foodTags: JSON.stringify(["Seafood", "West Coast", "Nordic"]),
      latitude: 57.6920,
      longitude: 11.9280,
      isExclusive: true,
      city: "Göteborg",
    },
    {
      name: "Toso",
      address: "Magasinsgatan 3, 411 18 Göteborg",
      cuisine: "Asian Fusion",
      neighborhood: "Centrum",
      rating: 4.4,
      reviewCount: 478,
      priceLevel: 2,
      image: "https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=800",
      description: "Trendy Asian fusion spot on Magasinsgatan with creative cocktails and shareable plates. A go-to for vibrant flavors in a buzzing atmosphere.",
      tags: JSON.stringify(["Asian Fusion", "Cocktails", "Trendy"]),
      timesBookedOnReslot: 19,
      seatType: "Båda",
      instagram: "@toso_gbg",
      website: "https://toso.se",
      vibeTags: JSON.stringify(["Trendy", "Buzzing", "Social"]),
      goodForTags: JSON.stringify(["After Work", "Friends Dinner", "Casual Date"]),
      foodTags: JSON.stringify(["Asian", "Fusion", "Cocktails", "Sharing"]),
      latitude: 57.7040,
      longitude: 11.9680,
      isExclusive: false,
      city: "Göteborg",
    },
    // Malmö
    {
      name: "Vollmers",
      address: "Tegelgårdsgatan 5, 211 33 Malmö",
      cuisine: "New Nordic",
      neighborhood: "Centrum",
      rating: 4.8,
      reviewCount: 534,
      priceLevel: 4,
      image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
      description: "Two Michelin-starred restaurant in the heart of Malmö. Brothers Mats and Ebbe Vollmer create extraordinary seasonal menus from the finest Skånska produce.",
      tags: JSON.stringify(["Michelin Star", "Tasting Menu", "Nordic"]),
      timesBookedOnReslot: 29,
      seatType: "Inomhus",
      instagram: "@vollmers_malmo",
      website: "https://vollmers.nu",
      vibeTags: JSON.stringify(["Sophisticated", "Elegant", "Intimate"]),
      goodForTags: JSON.stringify(["Special Occasions", "Anniversary", "Date Night"]),
      foodTags: JSON.stringify(["Nordic", "Seasonal", "Skånsk", "Tasting Menu"]),
      latitude: 55.6050,
      longitude: 13.0038,
      isExclusive: true,
      city: "Malmö",
    },
    {
      name: "Bastard",
      address: "Mäster Johansgatan 11, 211 21 Malmö",
      cuisine: "New Nordic",
      neighborhood: "Centrum",
      rating: 4.6,
      reviewCount: 867,
      priceLevel: 3,
      image: "https://images.unsplash.com/photo-1533777324565-a040eb52facd?w=800",
      description: "Rustic New Nordic bistro with an open kitchen and communal energy. Bold flavors, nose-to-tail cooking, and one of Malmö's best natural wine selections.",
      tags: JSON.stringify(["Nordic", "Bistro", "Natural Wine"]),
      timesBookedOnReslot: 42,
      seatType: "Inomhus",
      instagram: "@bastard_malmo",
      website: "https://bastardrestaurant.se",
      vibeTags: JSON.stringify(["Rustic", "Buzzing", "Bold"]),
      goodForTags: JSON.stringify(["Friends Dinner", "Date Night", "Food Enthusiasts"]),
      foodTags: JSON.stringify(["Nordic", "Nose-to-tail", "Natural Wine"]),
      latitude: 55.5980,
      longitude: 13.0010,
      isExclusive: false,
      city: "Malmö",
    },
    {
      name: "Lyran Mat & Bar",
      address: "Baltzarsgatan 18, 211 36 Malmö",
      cuisine: "Modern Swedish",
      neighborhood: "Centrum",
      rating: 4.5,
      reviewCount: 534,
      priceLevel: 3,
      image: "https://images.unsplash.com/photo-1560053608-13721e0d69e5?w=800",
      description: "Modern Swedish cooking with Mediterranean flair in a lively bar-restaurant setting. Known for creative small plates and an excellent cocktail program.",
      tags: JSON.stringify(["Modern Swedish", "Cocktails", "Small Plates"]),
      timesBookedOnReslot: 31,
      seatType: "Båda",
      instagram: "@lyran_malmo",
      website: "https://lyranmalmo.se",
      vibeTags: JSON.stringify(["Lively", "Social", "Stylish"]),
      goodForTags: JSON.stringify(["After Work", "Friends Dinner", "Casual Date"]),
      foodTags: JSON.stringify(["Swedish", "Mediterranean", "Small Plates", "Cocktails"]),
      latitude: 55.6010,
      longitude: 13.0005,
      isExclusive: false,
      city: "Malmö",
    },
    {
      name: "Mineral",
      address: "Norra Skolgatan 26, 214 22 Malmö",
      cuisine: "Vegetarian Fine Dining",
      neighborhood: "Möllevången",
      rating: 4.4,
      reviewCount: 389,
      priceLevel: 3,
      image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
      description: "Malmö's premier vegetarian fine dining experience. Creative plant-based tasting menus that challenge expectations and celebrate seasonal Skåne produce.",
      tags: JSON.stringify(["Vegetarian", "Fine Dining", "Tasting Menu"]),
      timesBookedOnReslot: 22,
      seatType: "Inomhus",
      instagram: "@mineral_malmo",
      website: "https://mineralrestaurant.se",
      vibeTags: JSON.stringify(["Minimalist", "Creative", "Intimate"]),
      goodForTags: JSON.stringify(["Date Night", "Food Enthusiasts", "Special Occasions"]),
      foodTags: JSON.stringify(["Vegetarian", "Plant-based", "Tasting Menu", "Seasonal"]),
      latitude: 55.5910,
      longitude: 13.0060,
      isExclusive: false,
      city: "Malmö",
    },
  ];

  const createdRestaurants = [];
  for (const r of restaurants) {
    const created = await db.restaurant.create({ data: r });
    createdRestaurants.push(created);
    console.log(`Created restaurant: ${created.name}`);
  }

  const now = new Date();
  const reservationData = [
    { restaurantIndex: 0, time: "19:00", partySize: 2, daysFromNow: 1 },
    { restaurantIndex: 0, time: "20:30", partySize: 4, daysFromNow: 3 },
    { restaurantIndex: 1, time: "18:30", partySize: 2, daysFromNow: 1 },
    { restaurantIndex: 1, time: "19:00", partySize: 6, daysFromNow: 2 },
    { restaurantIndex: 2, time: "19:30", partySize: 4, daysFromNow: 2 },
    { restaurantIndex: 2, time: "20:00", partySize: 2, daysFromNow: 4 },
    { restaurantIndex: 3, time: "18:00", partySize: 2, daysFromNow: 1 },
    { restaurantIndex: 3, time: "19:00", partySize: 3, daysFromNow: 3 },
    { restaurantIndex: 4, time: "19:00", partySize: 2, daysFromNow: 2 },
    { restaurantIndex: 4, time: "20:00", partySize: 4, daysFromNow: 5 },
    { restaurantIndex: 5, time: "19:30", partySize: 2, daysFromNow: 1 },
    { restaurantIndex: 5, time: "20:00", partySize: 2, daysFromNow: 3 },
    { restaurantIndex: 6, time: "18:00", partySize: 4, daysFromNow: 1 },
    { restaurantIndex: 6, time: "19:30", partySize: 6, daysFromNow: 2 },
    { restaurantIndex: 6, time: "20:00", partySize: 2, daysFromNow: 4 },
    { restaurantIndex: 7, time: "18:00", partySize: 2, daysFromNow: 1 },
    { restaurantIndex: 7, time: "19:00", partySize: 2, daysFromNow: 2 },
    { restaurantIndex: 8, time: "19:00", partySize: 2, daysFromNow: 1 },
    { restaurantIndex: 9, time: "20:00", partySize: 4, daysFromNow: 2 },
    { restaurantIndex: 10, time: "19:30", partySize: 2, daysFromNow: 1 },
  ];

  const firstNames = ["Erik", "Anna", "Lars", "Sofia", "Johan", "Maria", "Oscar", "Emma", "Karl", "Linnea"];
  const lastNames = ["Svensson", "Johansson", "Lindberg", "Nilsson", "Bergström", "Andersson", "Pettersson"];

  for (let i = 0; i < reservationData.length; i++) {
    const rd = reservationData[i]!;
    const restaurant = createdRestaurants[rd.restaurantIndex];
    if (!restaurant) continue;
    const date = new Date(now);
    date.setDate(date.getDate() + rd.daysFromNow);
    date.setHours(0, 0, 0, 0);

    const firstName = firstNames[i % firstNames.length] ?? "Erik";
    const lastName = lastNames[i % lastNames.length] ?? "Svensson";

    await db.reservation.create({
      data: {
        restaurantId: restaurant.id,
        submitterPhone: `+4670${String(1000000 + i).slice(1)}`,
        submitterFirstName: firstName,
        submitterLastName: lastName,
        reservationDate: date,
        reservationTime: rd.time,
        partySize: rd.partySize,
        seatType: restaurant.seatType,
        nameOnReservation: `${firstName} ${lastName}`,
        status: "active",
        cancelFee: Math.random() > 0.5 ? Math.round(Math.random() * 500 + 200) : null,
        prepaidAmount: Math.random() > 0.7 ? Math.round(Math.random() * 1000 + 500) : null,
      },
    });
  }

  console.log(`Created ${reservationData.length} sample reservations`);

  // Missed/completed reservations for "Du missade" feature
  const missedData = [
    { restaurantIndex: 0, time: "19:30", partySize: 2, hoursAgo: 3 },
    { restaurantIndex: 3, time: "20:00", partySize: 4, hoursAgo: 8 },
    { restaurantIndex: 5, time: "18:30", partySize: 2, hoursAgo: 14 },
    { restaurantIndex: 8, time: "19:00", partySize: 6, hoursAgo: 20 },
    { restaurantIndex: 11, time: "20:30", partySize: 2, hoursAgo: 28 },
    { restaurantIndex: 13, time: "19:00", partySize: 3, hoursAgo: 40 },
  ];

  for (let i = 0; i < missedData.length; i++) {
    const md = missedData[i]!;
    const restaurant = createdRestaurants[md.restaurantIndex];
    if (!restaurant) continue;
    const claimedAt = new Date(Date.now() - md.hoursAgo * 60 * 60 * 1000);
    const createdAt = new Date(claimedAt.getTime() - (Math.random() * 30 + 2) * 60 * 1000);
    const resDate = new Date(claimedAt);
    resDate.setDate(resDate.getDate() + 1);
    resDate.setHours(0, 0, 0, 0);

    await db.reservation.create({
      data: {
        restaurantId: restaurant.id,
        submitterPhone: `+4670${String(2000000 + i).slice(1)}`,
        submitterFirstName: firstNames[(i + 5) % firstNames.length] ?? "Erik",
        submitterLastName: lastNames[(i + 3) % lastNames.length] ?? "Svensson",
        reservationDate: resDate,
        reservationTime: md.time,
        partySize: md.partySize,
        seatType: restaurant.seatType,
        nameOnReservation: `${firstNames[(i + 5) % firstNames.length]} ${lastNames[(i + 3) % lastNames.length]}`,
        status: "completed",
        claimerPhone: `+4670${String(3000000 + i).slice(1)}`,
        claimedAt,
        creditStatus: "awarded",
        createdAt,
      },
    });
  }
  console.log(`Created ${missedData.length} missed/completed reservations`);

  console.log("Seed complete!");
}

seed()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
